### ISSUE TITLE
[FR] 一个笔记多个编号

### ISSUE THREAD

**Issue by wwjCMP** [PKM-er/obsidian-zettelkasten-navigation#12]
假如说在一棵树上，卡片的编号需要是唯一的，为什么卡片不可以具有多个树的位置信息。即一个卡片可以从属于多棵树。

比如
A_1_1_2
B_1_3_2

在分别生成A、B两个树的时候，具有两个编号的笔记的位置也是唯一确定的。而且不会相互干扰。生成哪棵树都是由第一个字符串决定的。

假如说，选定具有多个编号的卡片作为入口，加一个切换就行，比如默认以第一个编码作为入口，然后在界面可以操作切换所在树就行了。

**Comment by terrychenzw** [comment]
这个问题我有思考过，在技术上是可以实现的。但我更关注的是这个需求背后的东西。

这个需求的前提是：**一个笔记可以不做任何修改，就能直接被用在不同分支/树里面。**

之前有其他网友提过类似的问题，我当时的回答：

>**A网友**：有一个问题，一个卡片笔记编码之后，怎么用到另外一棵树上？
>
>**我的回答**：不同分支/树的语境/上下文一定是不同的, A树下一张卡片a1不能原封不动挂在B树下。我一般是在B棵树下建一张新卡片b1,按B树的语境/上下文的需要来重新表述a1的内容/部分内容。然后在b1的内容中给重新表述的语句加绿色下划线,并在卡片底部加绿色的a1链接，表示b1引用到a1卡片或a1所在分支。相似的内容有a1和b1两个版本是有价值的，因为Zettelkasten的目的是发展想法，而不仅仅是存储信息。 a1和b1都在发展其所在树A和B。

>**B网友**：想咨询下，这种树的笔记方式会不会出现一种情况建立的庞大的树，突然发现有了比当前顶点更顶层的知识结构。那么这个节点是放在哪里呢？重构树带来的工作量太大了。
>
>**我的回答**：不要重构，重构会将毁灭了你想法发展的轨迹。一个节点的笔记内容，跟很多树/分支有相关，这个太常见了，而且要积极发现这些相关性。我现在的做法是在另一个相关的分支下，建一个新的笔记，结合这个分支的语境重新表述一次，然后链接(引用）到原来节点。每个分支的语境都是不一样的，同样一个内容，在不同语境下的表述也是不同的。重点是发展分支，因此使用自己的语言，按当前分支的语境来表述很重要。
>
>举例：视频中说的“大杂烩”这一张卡片（编号：TP319-1-1-1A-1C），如果在原分支上，这张卡片所在分支的语境是关于“大杂烩”的，表述都是跟大杂烩相关。而在这次分享的大纲里（也是一个主笔记文件），我是将它作为一个集合卡的例子，更关注的是它的形式，而不是内容。它在这个大纲笔记里的表述是：集合卡例子：[[TP319-1-1-1A-1C]]。

前面2个回答都是基于我对zettelkasten的理解：**是发展想法，而不是信息存储与归类。发展想法的话，就会要求我们要基于另一个分支的语境来重新表述**。之前有个网友使用“**跨语境翻译**”这个词来形容，我觉得是比较形象的。

当然，这只是基于zettelkasten的使用场景，跟你的实际场景不一定相同。十分欢迎您表达自己的实际应用场景，相互交流与学习。

**Comment by wwjCMP** [comment]
我的使用场景，之前也说过几次了。我更加在意的是知识的再线性化与知识复用。
这两点相互依赖，如果不能在多个树中复用，那实现不了再线性化（结构化）。
如果不能再线性化，那就实现不了知识的复用。
我认为就像写文章一样，通过将知识点线性输出来实现，再线性化的过程就是再创作的过程。

**Comment by terrychenzw** [comment]
如果是写文章的场景，我会建议建一个新的主笔记作为文章大纲笔记，在这个笔记里，按文章的逻辑来重新笔记关系。也可以使用一些插件来展示这个笔记的大纲或生成思维导图。

这个大纲笔记也是主笔记，你可以选择一个你喜欢的位置（编号）来将它添加到zettelkasten当中。有需要也可以建一个关键词索引来指向这个大纲主笔记。以下是我的一个大纲笔记例子：

![image](https://github.com/terrychenzw/obsidian-zettelkasten-navigation/assets/114856910/88b26fde-b38c-45c5-b31d-9307762ca070)

这一种主笔记可以称为集合卡，基于特定主题/话题 对笔记关系进行重新定义。

**Comment by wwjCMP** [comment]
只是用写文章举例，我的需求一般都是写长文，所以用longform比较多。

主要说的还是知识管理的事，知识点在不同的线性结构中被复用。因为人对线性结构的知识理解最好。

**Comment by wwjCMP** [comment]
从知识管理的角度，一新棵树就要对同样的信息做新的表述，会给知识库带来极大的信息冗余

**Comment by terrychenzw** [comment]
> 从知识管理的角度，一新棵树就要对同样的信息做新的表述，会给知识库带来极大的信息冗余。以及使用这个系统的成本。

新的表述不是旧卡片所有内容全部重新表述，更多是旧卡片跟新树/分支的关系表述。我大部分时候就是一句话后加旧卡片的链接。当然这个只是我的场景。

链接/引用也可以将旧卡片关联到新树/分支，这个是纸笔时代的做法。而在这个插件当前的分支视图，无法显示链接/引用的卡片。只有在打开具体一个卡片后，才能在右侧的局部视图的出链视图中看到。

我理解卡片复用，再组织的需求。我的做法前面也提到，就是建大纲笔记，在一个笔记页面来再组织不同卡片。再组织通常会频繁地调整和重构笔记之间的关系，我个人觉得在大纲笔记页面里操作会比调整卡片ID来得方便。当然这个只是基于我的场景。

卡片支持多个ID确实是一个比较创新的想法，我还要再思考一下。

**Comment by cygroup** [comment]
按照zettelkasten的观点，卡片放在什么位置是不重要的，关键是能够链接到它，可以通过卡片链接对其他树中的卡片进行引用，也可以使用MOC卡片的方式来组织不同树中的相关卡片，不同的MOC可以是不用的场景，比如不同题目、不同角度的文章大纲，或是不同知识领域里知识点的组织整合，这与一开始通过zettelkasten发展卡片树是不一样的，而且在一开始也不太可能就能知道大构图，或是知识将如何被重复使用，重构编码肯定不是聪明的方法，MOC却可以是一个不错的选择，zettelkasten只是知识管理的一种方法论，任何一种方法论肯定都没法覆盖所有的需求，zettelkasten与双链的结合使用是必需的。

**Comment by wwjCMP** [comment]
> 按照zettelkasten的观点，卡片放在什么位置是不重要的，关键是能够链接到它，可以通过卡片链接对其他树中的卡片进行引用，也可以使用MOC卡片的方式来组织不同树中的相关卡片，不同的MOC可以是不用的场景，比如不同题目、不同角度的文章大纲，或是不同知识领域里知识点的组织整合，这与一开始通过zettelkasten发展卡片树是不一样的，而且在一开始也不太可能就能知道大构图，或是知识将如何被重复使用，重构编码肯定不是聪明的方法，MOC却可以是一个不错的选择，zettelkasten只是知识管理的一种方法论，任何一种方法论肯定都没法覆盖所有的需求，zettelkasten与双链的结合使用是必需的。

我看中的是本插件结构化提取的部分，构成了知识复用的核心部分。知识库是一个无穷维的大脑。而我们关注的是以所关注需求为核心知识树。所以树的作用是以一种结构的化的方式从知识大脑中重新提取。MOC的核心问题的无法和双链系统区分开来，即无法做到有效结构化提取。而本插件提供了这样一种可能。

**Comment by wwjCMP** [comment]
以这种思路往下走，一棵树便需要一套编码。我们只需要基于我们的知识大脑，不断地构建我们的各种树。这样树和大脑是共生的，同时也是解耦的。我们在专注于其中一方面的时候，不会受到另外一套系统的影响。

**Comment by cygroup** [comment]
> > 按照zettelkasten的观点，卡片放在什么位置是不重要的，关键是能够链接到它，可以通过卡片链接对其他树中的卡片进行引用，也可以使用MOC卡片的方式来组织不同树中的相关卡片，不同的MOC可以是不用的场景，比如不同题目、不同角度的文章大纲，或是不同知识领域里知识点的组织整合，这与一开始通过zettelkasten发展卡片树是不一样的，而且在一开始也不太可能就能知道大构图，或是知识将如何被重复使用，重构编码肯定不是聪明的方法，MOC却可以是一个不错的选择，zettelkasten只是知识管理的一种方法论，任何一种方法论肯定都没法覆盖所有的需求，zettelkasten与双链的结合使用是必需的。
> 
> 我看中的是本插件结构化提取的部分，这构成了知识复用的核心部分。知识库是一个无穷维的大脑。而我们所关注的只是以需求为核心的知识树。所以树的作用是以一种结构化的方式从知识大脑中将相关知识提取出来。MOC的核心问题的无法和双链系统区分开来，即无法做到有效结构化提取。而本插件提供了这样一种可能。

你的需求没问题，只是多棵树如果要交叉在一起，那就是图了，即obsidian本身的关系图谱，这个插件的主要核心思路还是zettelkasten的树观点。

**Comment by cygroup** [comment]
> > 按照zettelkasten的观点，卡片放在什么位置是不重要的，关键是能够链接到它，可以通过卡片链接对其他树中的卡片进行引用，也可以使用MOC卡片的方式来组织不同树中的相关卡片，不同的MOC可以是不用的场景，比如不同题目、不同角度的文章大纲，或是不同知识领域里知识点的组织整合，这与一开始通过zettelkasten发展卡片树是不一样的，而且在一开始也不太可能就能知道大构图，或是知识将如何被重复使用，重构编码肯定不是聪明的方法，MOC却可以是一个不错的选择，zettelkasten只是知识管理的一种方法论，任何一种方法论肯定都没法覆盖所有的需求，zettelkasten与双链的结合使用是必需的。
> 
> 我看中的是本插件结构化提取的部分，这构成了知识复用的核心部分。知识库是一个无穷维的大脑。而我们所关注的只是以需求为核心的知识树。所以树的作用是以一种结构化的方式从知识大脑中将相关知识提取出来。MOC的核心问题的无法和双链系统区分开来，即无法做到有效结构化提取。而本插件提供了这样一种可能。

你的需求没问题，只是多棵树如果要交叉在一起，那就是图了，即obsidian本身的关系图谱，这个插件的主要核心思路还是zettelkasten的树观点。

**Comment by terrychenzw** [comment]
> > 按照zettelkasten的观点，卡片放在什么位置是不重要的，关键是能够链接到它，可以通过卡片链接对其他树中的卡片进行引用，也可以使用MOC卡片的方式来组织不同树中的相关卡片，不同的MOC可以是不用的场景，比如不同题目、不同角度的文章大纲，或是不同知识领域里知识点的组织整合，这与一开始通过zettelkasten发展卡片树是不一样的，而且在一开始也不太可能就能知道大构图，或是知识将如何被重复使用，重构编码肯定不是聪明的方法，MOC却可以是一个不错的选择，zettelkasten只是知识管理的一种方法论，任何一种方法论肯定都没法覆盖所有的需求，zettelkasten与双链的结合使用是必需的。
> 
> 我看中的是本插件结构化提取的部分，这构成了知识复用的核心部分。知识库是一个无穷维的大脑。而我们所关注的只是以需求为核心的知识树。所以树的作用是以一种结构化的方式从知识大脑中将相关知识提取出来。MOC的核心问题的无法和双链系统区分开来，即无法做到有效结构化提取。而本插件提供了这样一种可能。从这个角度讲，zette的核心优点是有限的结构，而不是当前双链带来无限的链接。



这里激发了我对双链和树的一些思考。

## 我对双链与树状结构的看法

双链形成的图谱之所以乱，就是因为我们用双链来表达事物之间的所有联系。事物之间的联系本身是十分丰富和多维的，都用单一的点与点连接的方式来表达显得十分简单粗暴。当笔记数量和链接多了之后，就会显得混乱和无序，一团糟。

相比之下，树状结构是一种有序的表达/呈现，有利于我们记忆和提取，具有很强的实用价值。

不过树状结构同样有它的问题：
1. 对新内容的准入门槛比双链高：一个新内容要进入树状结构，就要考虑它跟整个分支/树的关系。而双链只需要考虑跟另一个笔记的关系
2. 位置一旦确定就不宜修改：修改位置就要考虑整个分支/树的结构，代价太大。而使用双链后出现修改，只需要考虑2个笔记。

因此，双链比树状结构的对新内容的包容性更强，试错成本更低。

很多深刻的洞见是需要时间来发展的。有时，我们刚发现一些事物之间的联系，刚开始时并不会十分清晰。保留这些模糊的联系，就是保留将来继续发展这些联系的可能性，这个时候使用双链是合适的。也许将来的某一天，偶然之下回到这个双链，又有新的见解，就可以继续发展它。

所以，树和双链，都各有优缺点，这是它们的本质决定的。我的观点是合理利用其优势而规避其劣势。卢曼的zettelkasten也是包含着两种技术的。

## 关于使用多ID来替代（或部分替代）双链的使用

这个思路对我也是有一定吸引力的。其中之一就是，这是体现数字化优势的一个尝试，多ID在纸笔时代是很难实现的。

不过，下面这些问题我当前还在思考中：
1. 当被用在输出的场景，比如分配新ID来组织笔记形成文章大纲，会导致频繁修改ID
2. 一个主笔记因为要适用于不同分支，而修改原有的表述（删除/更改历史）
3. 分支发展的线性顺序和创建时间的线性顺序不一致
比如A3是A树下的第三个子节点，后被用在B树下，新ID为B1。这个时候，会出现B1（A3的复用）的创建时间比B先。时间顺序：B1->B, 分支顺序: B->B1。这一点主要是跟我将来想做的一个功能有些冲突，就是结合笔记的创建时间来动态显示分支的生长过程（对标关系图谱插件的动画功能）（解决方案也有，就是保留多个时间、但会导致程序逻辑和用户操作变得复杂）

我对数字化zettelkasten的期望是，可以保留不同思维链路的历史，以供将来的追溯。而时间线是记录历史的一个重要的维度。这是卢曼zettelkasten所缺乏的。

@wwjCMP @cygroup 谢谢你们的分享。

**Comment by wwjCMP** [comment]
> > > 按照zettelkasten的观点，卡片放在什么位置是不重要的，关键是能够链接到它，可以通过卡片链接对其他树中的卡片进行引用，也可以使用MOC卡片的方式来组织不同树中的相关卡片，不同的MOC可以是不用的场景，比如不同题目、不同角度的文章大纲，或是不同知识领域里知识点的组织整合，这与一开始通过zettelkasten发展卡片树是不一样的，而且在一开始也不太可能就能知道大构图，或是知识将如何被重复使用，重构编码肯定不是聪明的方法，MOC却可以是一个不错的选择，zettelkasten只是知识管理的一种方法论，任何一种方法论肯定都没法覆盖所有的需求，zettelkasten与双链的结合使用是必需的。
> > 
> > 
> > 我看中的是本插件结构化提取的部分，这构成了知识复用的核心部分。知识库是一个无穷维的大脑。而我们所关注的只是以需求为核心的知识树。所以树的作用是以一种结构化的方式从知识大脑中将相关知识提取出来。MOC的核心问题的无法和双链系统区分开来，即无法做到有效结构化提取。而本插件提供了这样一种可能。从这个角度讲，zette的核心优点是有限的结构，而不是当前双链带来无限的链接。
> 
> @wwjCMP @cygroup 谢谢你们的分享。
> 
> 这里激发了我对双链和树的一些思考。
> 
> ## 我对双链与树状结构的看法
> 双链形成的图谱之所以乱，就是因为我们用双链来表达事物之间的所有联系。事物之间的联系本身是十分丰富和多维的，都用单一的点与点连接的方式来表达显得十分简单粗暴。当笔记数量和链接多了之后，就会显得混乱和无序，一团糟。
> 
> 相比之下，树状结构是一种有序的表达/呈现，有利于我们记忆和提取，具有很强的实用性。
> 
> 不过树状结构同样有它的问题：
> 
> 1. 对新内容的准入门槛比双链高：一个新内容要进入树状结构，就要考虑它跟整个分支/树的关系。而双链只需要考虑跟另一个笔记的关系
> 2. 位置一旦确定就不宜修改：修改位置就要考虑整个分支/树的结构，代价太大。而使用双链后出现修改，只需要考虑2个笔记。
> 
> **因此，双链比树状结构对新内容的包容性更强，试错成本更低。**
> 
> 很多深刻的洞见是需要时间来发展的。有时，我们刚发现一些事物之间的联系，刚开始时并不会十分清晰。保留这些模糊的联系，就是保留将来继续发展这些联系的可能性，这个时候使用双链是合适的。也许将来的某一天，偶然之下回到这个双链，又有新的见解，就可以继续发展它。
> 
> **所以，树和双链，都各有优缺点，这是它们的本质决定的**。我的观点是合理利用其优势而规避其劣势。卢曼的zettelkasten也是包含着两种技术的。
> 
> ## 关于使用多ID来替代（或部分替代）双链的使用
> 这个思路对我也是有一定吸引力的。其中之一就是，这是体现数字化优势的一个尝试，多ID在纸笔时代是很难实现的。
> 
> 不过，下面这些问题我当前还在思考中：
> 
> 1. 当被用在输出的场景，比如分配新ID来组织笔记形成文章大纲，会导致频繁修改ID
> 2. 一个主笔记因为要适用于不同分支，而修改原有的表述（删除/更改历史）
> 3. 分支发展的线性顺序和创建时间的线性顺序不一致
>    比如A3是A树下的第三个子节点，后被用在B树下，新ID为B1。这个时候，会出现B1（A3的复用）的创建时间比B先。时间顺序：B1->B, 分支顺序: B->B1。这一点主要是跟我将来想做的一个功能有些冲突，就是结合笔记的创建时间来动态显示分支的生长过程（对标关系图谱插件的动画功能）（解决方案也有，就是保留多个时间、但会导致程序逻辑和用户操作变得复杂）
> 
> 我对数字化zettelkasten的期望是，可以保留不同思维链路的历史，以供将来的追溯。而时间线是记录历史的一个重要的维度。这是卢曼zettelkasten所缺乏的。

不知道是否有计划实现这个功能。使用了一段时间，发现这是妨碍我深度使用的主要问题。
关于时间信息，我觉得如果程序能实现自动写入功能就没什么问题。指定一个类型为列表的属性来填写时间信息。
当添加一个树的位置ID，自动根据添加的这个ID自动在时间属性里面生成一个字符串，这个字符串包含两种信息一个是所在的树、一个是添加的时间就行了。删除ID也是一样，删除对应的时间就行。

**Comment by terrychenzw** [comment]
> 不知道是否有计划实现这个功能。使用了一段时间，发现这是妨碍我深度使用的主要问题。
> 关于时间信息，我觉得如果程序能实现自动写入功能就没什么问题。指定一个类型为列表的属性来填写时间信息。
> 当添加一个树的位置ID，自动根据添加的这个ID自动在时间属性里面生成一个字符串，这个字符串包含两种信息一个是所在的树、一个是添加的时间就行了。删除ID也是一样，删除对应的时间就行。

这个需求会以【实验性功能】的形式做到插件里，预计12月份前会出一个初版（⚠【实验性功能】会存在较大的重构风险）

功能不算复杂，但要调整的代码比较多。基本上每个功能点都要过一次。

以下问题会先忽略掉
1. 局部关系图：
  - 打开一个多ID的笔记时，局部关系图怎样展示（暂时默认显示其中一个）
  - 当前笔记关联（入链或出链）到一个多ID的笔记时，局部关系图怎样展示（暂时默认显示其中一个）

2. 时间信息
  - 暂时先以多ID共用一个创建时间的方式处理。毕竟无论是手工还是自动，维护多个创建时间还是挺繁琐的。

**Comment by terrychenzw** [comment]
该需求已于 [1.0.2](https://github.com/PKM-er/obsidian-zettelkasten-navigation/releases/tag/1.0.2) 发布
