### ISSUE TITLE
[BUG] 不能增加笔记

### ISSUE THREAD

**Issue by wwjCMP** [PKM-er/obsidian-zettelkasten-navigation#28]
给新笔记进行编号，不能在插件中显示

**Comment by terrychenzw** [comment]
没理解问题。是指在关键词分支视图上无法创建新笔记？

**Comment by wwjCMP** [comment]
对，甚至新建一个分支都不行

**Comment by terrychenzw** [comment]
相似的需求其它网友有提过：https://github.com/PKM-er/obsidian-zettelkasten-navigation/issues/11

这个插件当前的定位是图谱（对标核心插件关系图谱），主要实现笔记关系的呈现。是否增加笔记的操作功能（创建/修改/删除），我还要再想想。

**Comment by wwjCMP** [comment]
> 相似的需求其它网友有提过：#11
> 
> 这个插件当前的定位是图谱（对标核心插件关系图谱），主要实现笔记关系的呈现。是否增加笔记的操作功能（创建/修改/删除），我还要再想想。

不是功能，是bug，我说的不是新建文件。就是形成图片

**Comment by terrychenzw** [comment]
笔记不能在视图显示：
1.点击主笔记检索按钮，看看目标主笔记是否能找到，
1.1.如果不能找到，检查插件设置的文件夹或者标签，看看目标主笔记是否与设置一致
1.2.如果能找到，但是无法跟已有且ID靠近的笔记生成分支，检查一下ID字符串是否符合字母数字的层级关系。

如果还是无法解决，请提供截图/视频等更详细信息说明。

**Comment by terrychenzw** [comment]
笔记不能在视图显示：
1.点击主笔记检索按钮，看看目标主笔记是否能找到，
1.1.如果不能找到，检查插件设置的文件夹或者标签，看看目标主笔记是否与设置一致
1.2.如果能找到，但是无法跟已有且ID靠近的笔记生成分支，检查一下ID字符串是否符合字母数字的层级关系。

如果还是无法解决，请提供截图/视频等更详细信息说明。

**Comment by wwjCMP** [comment]
![image](https://github.com/user-attachments/assets/0741f03a-0a65-488b-91d8-39982e504a47)
![image](https://github.com/user-attachments/assets/e89b220a-1924-40eb-a8aa-0893fda6f77e)

**Comment by terrychenzw** [comment]
字段类型的问题，你将ZK_ID的类型改为text

**Comment by wwjCMP** [comment]
> 字段类型的问题，你将ZK_ID的类型改为text

可以了
