### ISSUE TITLE
`zk-index-graph` 不显示节点之间的箭头

### ISSUE THREAD

**Issue by wither** [PKM-er/obsidian-zettelkasten-navigation#29]
你好，抱歉我的中文不好，我正在使用谷歌翻译。

我的 `zk-index-graph` 不显示节点之间的箭头。你能帮忙吗？谢谢。

![image](https://github.com/user-attachments/assets/5fd62528-9127-486b-8c35-6823b6d6bac2)

我附上了一张屏幕截图来展示这一点。

我的设置

![image](https://github.com/user-attachments/assets/b102cd2a-09e6-4bd0-b756-7abbf09a1fd8)
![image](https://github.com/user-attachments/assets/a7300aca-acbe-4296-9b49-ea7c7ed07568)

**Comment by terrychenzw** [comment]
English is fine here😊

There are 2 solutions to solve this problem:
1. remove the blanks(" - " -> "-") in filename of your main notes
2. choose 【" "blank】 as the separator in the settingTab

**Comment by wither** [comment]
Thank you so much! Your first suggestion fixed it :)
