### ISSUE TITLE
[FR] 主笔记位置提供多文件夹选项

### ISSUE THREAD

**Issue by Dirtyuri** [PKM-er/obsidian-zettelkasten-navigation#30]
非常好用的插件，感谢作者大大！就是想请教下，可否在主笔记位置的设置那里添加多个文件夹的选项？因为我先前的主笔记或者说卡片放在两个文件夹里，如下图所示（文件夹D存放的是一些专有名词性质的卡片，其实和E一样也是“卡片盒”），量都比较大了，重新移动十分不便。假如在实验性功能里加上从多个文件夹读主笔记的选项，就方便许多。

![1729043389786(1)](https://github.com/user-attachments/assets/1581742a-743d-4123-acc7-ac7855352692)

**Comment by terrychenzw** [comment]
如果是跨文件夹的，当前可以使用标签。在所有的主笔记打上同一个标签，文件夹留空。

**Comment by terrychenzw** [comment]
> 如果是跨文件夹的，当前可以使用标签。在所有的主笔记打上同一个标签。
> 
> 插件的主笔记设置页里，文件夹留空，指定主笔记的标签

第二个方案就是将它们作为子文件，创建一个新文件夹包含它们

**Comment by Dirtyuri** [comment]
> 如果是跨文件夹的，当前可以使用标签。在所有的主笔记打上同一个标签。
> 
> 插件的主笔记设置页里，文件夹留空，指定主笔记的标签

好的，就这样办，再次感谢~
