### ISSUE TITLE
分支颜色，字体颜色是否可以修改自定义或者提供选项

### ISSUE THREAD

**Issue by barye81** [PKM-er/obsidian-zettelkasten-navigation#32]
分支颜色，字体颜色是否可以修改自定义或者提供选项，现在默认是黄色

**Comment by terrychenzw** [comment]
字体颜色调整可以自行修改插件的style.css文件，或自行创建css snippet来调整。比如，要修改抬头区域的字体颜色，可以在插件style.css文件找到对应的容器.zk-index-toolbar，在里面增加 color: read;（将字体设置为红色）。

分支节点颜色下个版本将增加节点颜色设置选项，效果大致如下：

https://github.com/user-attachments/assets/71cd183d-f617-46d4-94f2-8c42069d1cbc

**Comment by terrychenzw** [comment]
分支颜色设置已于[1.0.3](https://github.com/PKM-er/obsidian-zettelkasten-navigation/releases/tag/1.0.3)发布
