### ISSUE TITLE
[Bug] 图标功能栏不会随着整个界面的缩放自动移动

### ISSUE THREAD

**Issue by wwjCMP** [PKM-er/obsidian-zettelkasten-navigation#33]
![image](https://github.com/user-attachments/assets/ab47637f-4703-4a81-beb1-b1722a007a0f)
 图标功能栏不会随着界面大小的缩放自动移动，而是会被遮盖起来

**Comment by terrychenzw** [comment]
没理解遮盖起来是什么意思。有动图或视频说明一下？

**Comment by wwjCMP** [comment]
> 没理解遮盖起来是什么意思。有动图或视频说明一下？

比如在右边的时候，展开侧边栏的时候这部分会被侧边栏遮住

**Comment by terrychenzw** [comment]
> > 没理解遮盖起来是什么意思。有动图或视频说明一下？
> 
> 比如在右边的时候，展开侧边栏的时候这部分会被侧边栏遮住

我操作侧边栏展开和隐藏，图标工具栏会自动跟随视图自动调整，没有出现你说的遮盖。需要确保：1.css.style没有做过任何修改；2.没有在css snippet里没有相同容器名的样式调整。

**Comment by wwjCMP** [comment]
> > > 没理解遮盖起来是什么意思。有动图或视频说明一下？
> > 
> > 
> > 比如在右边的时候，展开侧边栏的时候这部分会被侧边栏遮住
> 
> 我操作侧边栏展开和隐藏，图标工具栏会跟随视图自动调整，没有出现你说的遮盖。需要确保：1.style.css没有做过任何修改；2.css snippet里没有相同容器名的样式调整。

应该不是这两个的问题，css snippet 全关闭问题还在

**Comment by wwjCMP** [comment]
另外一个库没有问题，我自己排查一下吧
