### ISSUE TITLE
表格视图有点小了

### ISSUE THREAD

**Issue by wwjCMP** [PKM-er/obsidian-zettelkasten-navigation#35]
表格视图有点小了，看起来很累，至少应该和正常页面的字体大小一样吧。希望能增大，或者增加设置的选项。

**Comment by terrychenzw** [comment]
下个版本会将表格视图设置为固定宽度，各列宽度根据内容自适应

**Comment by terrychenzw** [comment]
该请求已于 [1.0.5](https://github.com/PKM-er/obsidian-zettelkasten-navigation/releases/tag/1.0.5) 发布
