### ISSUE TITLE
折叠开关打开后折叠功能无效

### ISSUE THREAD

**Issue by belialMoon** [PKM-er/obsidian-zettelkasten-navigation#37]
折叠开关打开后，是黄色的点，点击后变成绿色，但是子节点没有被折叠，是我的操作有问题吗？
![image](https://github.com/user-attachments/assets/eb65d4bc-7e94-460a-a650-b8c57654d837)
另外希望增加折叠、展开的功能，比如全部折叠、全部展开的选项，谢谢

**Comment by terrychenzw** [comment]
该bug已于 [1.0.5](https://github.com/PKM-er/obsidian-zettelkasten-navigation/releases/tag/1.0.5) 修复
