### ISSUE TITLE
1.0.5表格视图编号排序错乱

### ISSUE THREAD

**Issue by Dirtyuri** [PKM-er/obsidian-zettelkasten-navigation#38]
![1733017527532](https://github.com/user-attachments/assets/a90a9eb8-6874-4879-8426-9c449f18dcc0)
如上图所示。
p.s. 新的路线图风格非常赞，同一数字或字母层级的笔记之间联系更一目了然了，跟结构图也是相辅相成。

**Comment by terrychenzw** [comment]
该 bug 已于 [1.0.6](https://github.com/PKM-er/obsidian-zettelkasten-navigation/releases/tag/1.0.6) 修复。
