### ISSUE TITLE
Invalid main note when using "Option 2: Metadata is note ID"

### ISSUE THREAD

**Issue by groepl** [PKM-er/obsidian-zettelkasten-navigation#39]
From: https://forum.zettelkasten.de/discussion/comment/22190/#Comment_22190

My problem may result on my usage of "Option 2: Metadata is note ID":
![image](https://github.com/user-attachments/assets/0086763a-5bac-4c2f-9672-ec9a4c538598)

"Invalid main note" is shown as an error message:
![image](https://github.com/user-attachments/assets/4b72c475-4378-4156-a6ed-9b59c58e6556)

Here is my YAML in frontmatter:
```
---
tags:
  - type/note
  - theme/zettelkasten
  - structure/versus
  - structure/sequence
  - sequence/folgezettel
  - sequence/trainsofthought
aliases: 
lead: "**Folgezettel** is highly structured, with each note following a logical and direct continuation from the previous one. **Trains of thought** are a more informal process. They're part of everyday thinking and brainstorming."
visual: "![[image.jpg]]"
created: 2024-10-18, 15:31
modified: 2024-12-05, 19:41
sequence_id: Folgezettel
note_id: 1.2
template_type: Note
template_version: "1.30"
license: © 2022-2024 by Edmund Gröpl under CC BY-NC-SA 4.0
view_count: 11
---
```

**Comment by terrychenzw** [comment]
@groepl 

Probable the property type of your "note_id" is "Number".

You can change it from "Number" to "Text" or just upgrade to the latest [1.0.7](https://github.com/PKM-er/obsidian-zettelkasten-navigation/releases/tag/1.0.7) version.

**Comment by groepl** [comment]
I've changed both:
- property type from 1.30 (number) to "1.30" (text)
- upgraded to 1.0.7

The error message is gone. But the visual stays empty: No results found.

<img width="1634" alt="image" src="https://github.com/user-attachments/assets/63be7126-e3b4-41f4-9792-151209caa51b" />

My main notes are all in the "3_Permanent Notes" folder 

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/ef39fdb1-0301-490c-8755-ad35a99b9c20" />

The list of Structures is visible:

<img width="1630" alt="image" src="https://github.com/user-attachments/assets/129da179-1e12-4c1f-bf9e-81a4f0e981a1" />
